# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: ThinkVoice - Multi Channel Contact Center Software - Twilio Integration Services
email: info@thinkvoice.net
description: > # ThinkVoice is a leading provider of mulitchannel contact center solutions and Twilio Integration Services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thinkvoice.net" # the base hostname & protocol for your site
enforce_ssl: thinkvoice.net
twitter_username: ThinkVoiceHQ
github_username:  ThinkVoice
facebook_page_name: ThinkVoice
facebook_app_id: 203507920034510
facebook_page_id: 984809268262771
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:categories/:year/:month/:day/:title
# Build settings
markdown: kramdown
bot: true
gems:
  - jekyll-paginate
  - jekyll-redirect-from
